name: Frigate Event Manager
description: Notifications intelligentes pour les événements Frigate
version: 0.0.0 # x-release-please-version
slug: frigate-event-manager
url: https://github.com/trowaflo/frigate-event-manager
arch:
  - amd64
  - aarch64
init: false
ingress: true
ingress_port: 5555
homeassistant_api: true
map:
  - config:ro
options:
  mqtt_broker_url: ""
  mqtt_topic: frigate/reviews
  mqtt_client_id: frigate-event-manager
  severity_filter:
    - alert
    - detection
  cooldown: 30
  debounce: 5
  ttl: 30
  notify_service: persistent_notification
  frigate_url: ""
  api_port: 5555
  presign_ttl: 60
schema:
  mqtt_broker_url: str
  mqtt_topic: str?
  mqtt_client_id: str?
  mqtt_username: str?
  mqtt_password: password?
  notify_service: str?
  severity_filter:
    - str
  cameras:
    - str?
  cooldown: int?
  debounce: int?
  ttl: int?
  frigate_url: url?
  frigate_user: str?
  frigate_password: password?
  media_base_url: url?
  api_port: "int(1,65535)?"
  presign_ttl: "int(1,1440)?"
  persist_events: bool?
