name: HACS Validation

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  hacs:
    name: hacs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: hacs/action@d556e736723344f83838d08488c983a15381059a # 22.5.0
        with:
          category: integration
