name: HACS Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  hacs:
    name: hacs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: hacs/action@d556e736723344f83838d08488c983a15381059a # 22.5.0
        with:
          category: integration
