name: Release

on:
  push:
    branches: [main]

permissions: read-all

jobs:
  release:
    uses: trowaflo/github-actions/.github/workflows/release.yml@745d89e5792c3f9dd0c62e33a1065afd2eadc7a7 # v3.0.0
    permissions:
      contents: write
      pull-requests: write
    with:
      enable_release_please: true
