name: Release

on:
  push:
    branches: [main]

permissions: read-all

jobs:
  release:
    uses: trowaflo/github-actions/.github/workflows/release.yml@d51fc48891c455f85a902e3d23f8ac7a52ef273e # v1.1.0
    permissions:
      contents: write
      pull-requests: write
    with:
      enable_release_please: true
