name: PR Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  actions: read
  contents: read
  pull-requests: write
  security-events: write

jobs:
  python:
    uses: trowaflo/github-actions/.github/workflows/ha-integration.yml@main
    with:
      component_name: frigate_event_manager

  markdown:
    if: github.event_name == 'pull_request'
    uses: trowaflo/github-actions/.github/workflows/lint-markdown.yml@main

  kics:
    if: github.event_name == 'pull_request'
    uses: trowaflo/github-actions/.github/workflows/kics.yml@main
