name: PR Validation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - feat/python-migration

permissions:
  actions: read
  contents: read
  pull-requests: write
  security-events: write

jobs:
  python:
    uses: trowaflo/github-actions/.github/workflows/ha-integration.yml@main
    with:
      component_name: frigate_event_manager

  markdown:
    uses: trowaflo/github-actions/.github/workflows/lint-markdown.yml@main
